# ------------------------------------------------------------
# Default Site - Custom 404 Page
# ------------------------------------------------------------

server {
  listen 80 default;
#listen [::]:80 default;

  server_name default-host.localhost;
  access_log /data/logs/default-host_access.log combined;
  error_log /data/logs/default-host_error.log warn;

  root /data/nginx/custom;

  include conf.d/include/letsencrypt-acme-challenge.conf;
  
  location / {
    try_files /404.html =404;
    add_header Content-Type "text/html; charset=utf-8";
  }

}
